services:
  ses:
    build: .
    restart: always
    ports:
      - '8000:8000'
    volumes:
      - ./database.db:/opt/web/database.db
    environment:
      - SECRET_KEY=your_secure_random_key_here
    init: true
